### ISSUE TITLE
I get an Invalid IP address after trying to connect

### ISSUE THREAD

**Issue by smartens83** [valknight/MCBedrockDNSGuide#1]
Hey there, 
are you still able to connect to your own server?
I've installed CoreDNS now and edited everything, but when I'm trying to connect to my server, it says, "Invalid IP address". 
Just wanted to confirm if this trick still works on your site.

**Comment by smartens83** [comment]
Nevermind I was kind of dumb ^^
I've entered the local ip-address in coredns and not the external url.
After inserting the external url, everything runs like a charm :-)
Thanks for your tutorial!

**Comment by valknight** [comment]
On this, should I make the external URL requirement clearer?
