### ISSUE TITLE
Does this require nintendo online subscription?

### ISSUE THREAD

**Issue by mkaatman** [valknight/MCBedrockDNSGuide#6]
I got this working but I had to setup nintendo online. Is it possible to achieve without it?

**Comment by valknight** [comment]
Hiya,

Yes, you will need Nintendo Switch Online. This project isn't a mod to the game, but instead just changes the IP address Minecraft receives for the official servers to that of your own server.

**Comment by mkaatman** [comment]
I wonder how plausible it would be to emulate Nintendo online just enough to trick the game into allowing you to connect to the Minecraft server list.

**Comment by valknight** [comment]
This would be out of scope for the purpose of this project. Feel free to do your own research into this though.

-v

**Comment by mkaatman** [comment]
Of course. Thanks.
